In [1]:
import tensorflow as tf

In [2]:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [12]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.0887232 ,  0.17844683,  0.9487586 ,  0.4770058 , -0.1684196 ,
         0.19393829, -0.02596359,  0.7867725 ,  0.6551477 , -0.47133005]],
      dtype=float32)

In [13]:
tf.nn.softmax(predictions).numpy()

array([[0.02492745, 0.08851212, 0.1912251 , 0.11930682, 0.06256919,
        0.08989397, 0.07214869, 0.16262797, 0.14257102, 0.04621769]],
      dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
loss_fn(y_train[:1], predictions).numpy()

2.4091244

In [16]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
             )

In [17]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 718us/step - loss: 0.4885 - accuracy: 0.8540
Epoch 2/5
1875/1875 [==============================] - 1s 621us/step - loss: 0.1565 - accuracy: 0.9542
Epoch 3/5
1875/1875 [==============================] - 1s 622us/step - loss: 0.1091 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 1s 617us/step - loss: 0.0886 - accuracy: 0.9740
Epoch 5/5
1875/1875 [==============================] - 1s 624us/step - loss: 0.0741 - accuracy: 0.9767


In [18]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0827 - accuracy: 0.9738


[0.08274663984775543, 0.973800003528595]

In [19]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.36984032e-07, 2.83688739e-10, 3.98541886e-07, 5.13337291e-05,
        1.04498849e-11, 6.63697904e-07, 1.45175094e-10, 9.99945998e-01,
        5.56823636e-08, 1.03437310e-06],
       [1.17892306e-07, 8.14190353e-05, 9.99912977e-01, 3.19523519e-06,
        1.74422190e-13, 2.02371621e-06, 2.36179787e-08, 3.62146619e-12,
        2.18177135e-07, 3.31095387e-14],
       [2.34697063e-06, 9.99400258e-01, 6.13376469e-05, 2.53407916e-06,
        5.24470634e-05, 8.58934072e-06, 3.06343754e-05, 3.37572361e-04,
        1.04164763e-04, 2.85154584e-07],
       [9.99499321e-01, 2.63506494e-10, 1.44831056e-05, 5.65258517e-07,
        2.97511315e-06, 2.10911912e-05, 3.38864018e-04, 1.21085977e-04,
        1.21348094e-07, 1.45264221e-06],
       [4.27487021e-06, 2.84271584e-09, 2.69706311e-06, 9.56474580e-08,
        9.98451471e-01, 8.40994403e-07, 2.66545442e-07, 4.68174549e-04,
        1.82170902e-06, 1.07052526e-03]], dtype=float32)>